### ISSUE TITLE
Could you make a semver release?

### ISSUE THREAD

**Issue by Genkilabs** [jgubman/videojs-airplay#2]
This looks pretty cool, I'm going to give it a go.
If you get a chance, could you make a semantic versioned release of dist files. If you do that then services which use bower conventions, like the fantastic rails-assets.org can pick this up and people can install it in frameworks in a more maintainable way than just downloading it.

Take a look at the videojs releases page for what I'm talking about:
https://github.com/videojs/video.js/releases
Having it there means it can be automatiaclly updated with correct dependencies like this:
https://rails-assets.org/#/components/videojs

**Comment by jgubman** [comment]
done, thanks
