### ISSUE TITLE
videojs.plugin() is deprecated

### ISSUE THREAD

**Issue by PimHaarsma** [jgubman/videojs-airplay#7]
With Video.js version 6: 
"VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead"

Fix could be something like this:
https://github.com/googleads/videojs-ima/pull/382/files

**Comment by treyhoover** [comment]
👍 

Happy to submit a PR if you'd like.

**Comment by jgubman** [comment]
Ya, a PR would be great, thanks!

**Comment by treyhoover** [comment]
Opened PR #8 :)

**Comment by jayson04** [comment]
thank you sir
